#GET http://localhost:3001/api/persons/123

POST http://localhost:3001/api/persons
Content-Type: application/json

{
"number": "1233333",
"name": "J"
}



#DELETE http://localhost:3001/api/persons/2

#GET http://localhost:3001/api/persons/123